### ISSUE TITLE
JMOL FILTER fails to open temp file

### ISSUE THREAD

**Issue by srfdino** [geoffrowland/moodle-filter_jmol#17]
The viewer shows a error message: the file under filter/jmol/temp is not found.

The error comes up In a Moodle installation with several Web front-ends, not in a single server Moodle.

![jmol_error](https://cloud.githubusercontent.com/assets/14875086/10140248/e6734fd0-6606-11e5-973a-688b4b937bbf.png)

**Comment by geoffrowland** [comment]
Hmmm

I have only ever tested this on a singe server Moodle, not an installation with several Web front ends.
May need a re-design. Files *should* be automatically recopied across to the filter/jmol/temp folder if they exist in the Moodle filesystem but are missing from the temp folder. This is required for jsmol's jsmol.php to load binary format files across browsers.

**Comment by srfdino** [comment]
Hi Geoff!!

Thanks for your fast answer!

The point is that both the filter/jmol/temp AND the temp folder are 
local to the front-end,
I think, later the JS running on the browser maybe can not find the file.

I don't know if it is possible to get the file directly with 
pluginfile.php (Moodle filesystem) from the JS...

Anyway, It is not being an urgent issue for me now, but I think it is 
important for big organisations.

If I can make any specific test for you, just let me know.

Best regards,

Dino.


Geoff Rowland escribió:

**Comment by geoffrowland** [comment]
Dino

Thanks for the heads-up. I'm aware that the Jmol/JSmol filter is used by some larger institutions.

The filter/jmol/temp folder was set up as a workaround for the fact that JSmol could not work directly ith the Moodle file api for some file-type, browser combinations. May need a bit of a rethink. Perhaps a 'central' temp folder or, as you suggest, getting JSmol to work directly with pluginfile.php, 

If any progress with this, may well take you up on your offer of testing.

Geoff

**Comment by geoffrowland** [comment]
Just a quick follow-up to check this really is an issue with multiple Web front-ends. Similar symptoms were reported in:

https://moodle.org/mod/forum/discuss.php?d=319666#p1284246

These turned out to be a file-extension naming issue. Although Jmol/JSmol, itself, detects the file-type on loading of the file, irrespective of the file-extension, the Moodle filter need a precise and appropriate extension (e.g. .mol, .pdb, .cif, .pdb.gz, .pdb.png) as it needs to filter *before* loading by Jmol/JSmol.

More details in the above Moole forum thread

**Comment by srfdino** [comment]
Hi!

In our case I think its is not an issue with the file extension.

We tested in two situación with the same ".mol" file:
In the production platform (several front-ends) it fails.
In the pre-production platform (mono-server) it works.

Our versions are:
Moodle 2.9.1+ (Build: 20150711)
fiter_jmol 5.0 (Build: 2015090900)

(Thanks!!)


Geoff Rowland escribió:

**Comment by PatLemaire** [comment]
Hi,
Since the update, we have exactly the same error with our Moodle 2.7.10+ and Jmol 5.0 (Build: 2015091800).
It only happens in questions. All other resources are OK.
![2015-10-05_14-07-26](https://cloud.githubusercontent.com/assets/8931218/10280043/92369c1a-6b6a-11e5-9b7c-681548c5a6e7.png)
This seems an important issue.
Thanks in advance.

Regards,
Patrick

**Comment by geoffrowland** [comment]
OK I already fixed a similar issue with JSmol instances in Page resources. The Moodle filesystem has a few idiosyncrasies! I'll look into a fix.

**Comment by PatLemaire** [comment]
If I could help in any way...

**Comment by geoffrowland** [comment]
Can confirm the issue with Quiz Questions. JSmol instances work in a Quiz description but NOT in individual quiz Questions. Suspect a difference in the equivalent to the pluginfile() function (quiz_pluginfile? or quiz_question_pluginfile?). Will continue to investigate...

**Comment by PatLemaire** [comment]
In filter/jmol/filter.php, on lines 188->190, it says that MOODLE API should copy the file to a temporary physical filesystem (supposed to be : filter/jmol/temp) but I see nothing there. The copy seems to fail.

**Comment by geoffrowland** [comment]
Exactly! For Quiz Questions the file address the filter is trying to copy from is 'wrong' because the Moodle File API is not 'standard' for Quiz Questions. So, the filter can't find the file to copy to the /filter/jmol/temp folder. I'm trying to understand how the Quiz Question File API  works to sort a hack!

**Comment by srfdino** [comment]
Hi!

Geoff,
I can see some advances here :-)

I'd like to contribute from my case.
My case is happening just with jmol in a label in a course view page.

Anyway, I confirm the similar problem with jmol in the description of a question.
(The one your are chasing).
This happens both with several front-ends or a single server Moodle setup.

**Comment by geoffrowland** [comment]
Yes, that makes sense. There are two different issues here (though similar symptoms). A specific issue with Quiz Questions and a more general problem with multiple web front ends. The Quiz Question issue *should* be easier to sort...

**Comment by PatLemaire** [comment]
@srfdino : Is this an "old" label you are talking to ?
Because on my platform I noticed that the "old" filters were to be reintroduced to operate. New ones work great. And by old I mean those that existed before the update. 
It works fine but everything should be reintroduced (not really easy to do)...

**Comment by geoffrowland** [comment]
Hi @PatLemaire and @srfdino 
Just updated the GitHub master branch (lib.php and version.php) to, hopefully, fix the issue with Quiz Questions. 
Let me know if it works for you.

**Comment by PatLemaire** [comment]
Yesssss! Welldone. Everything seems to work fine. Good job and many thanks from teachers of my university.
I'll let you know if something goes wrong.

Cheers!
Patrick

**Comment by srfdino** [comment]
I'm on the way ...
I'll let you know ...

**Comment by srfdino** [comment]
Hi!

Geoff (& Patrick),

Good!

Everything right, even in the question text,  in the mono server environment.
Sadly, it is still failing in the multi server environment.

I'm afraid the issue about the filter/jmol/temp directory is still there.

Thanks!!
Dino.

**Comment by srfdino** [comment]
Hi!
@PatLemaire, about your comment.
No, I created a clean new label for the test.

**Comment by jmbragg** [comment]
Before I found this issue I sent a message to Geoff through moodle.org.  Here is a summary so far.

My server is a single server.
I had problems displaying Jmol filtered items in a Book with the same error message as described already in this thread.
I've updated to the latest Master here on Github.
I was still getting the same error but realized that there was a permissions issue.  I have my permissions set such that apache does NOT have write access to the moodle code.  This has never been required before and I'm a bit paranoid.  I added the appropriate permissions.
The issue still existed after this so I tried creating a brand new Book chapter and it worked.  From some subsequent testing I realized that it was failing on my older files because they are aliased into a user level file system repository.  If I chose not to alias them then it works just fine.

So, a question then as a non-developer:
Why are these files being created in a temp file in the moodle code folder?  Why aren't they being created in a temp file in the moodledata folder?  That seems like the place they're supposed to be.

**Comment by geoffrowland** [comment]
Hi @jmbrag

The files are copied to a temp folder in the plugin folder as that it is the only way that I can (yet) get JSmol to read them. This is related to difficulties in JSmol JavaScript reading binary format files (e.g. .pse, .pdb.png, .mol.png) with some browsers.

See: http://wiki.jmol.org/index.php/Jmol_JavaScript_Object#Reading_binary_files.

I have been 'wrestling' with code which both recognises the Moodle file API and does the necessary base64 encoding of binary file data, but have (so far) been unsuccessful with this. So, the directly web-accessible temp folder is a workaround.

You are quite correct that it is recommended that apache does not have access to the moodle code.

See: https://docs.moodle.org/29/en/Installing_Moodle#Download_and_copy_files_into_place.

However, it also states that if you use the built-in Moodle plugin installer GUI, you DO need to make make the directory writeable by the web server user.  I have been using the plugin-installer on my development moodle instances so had not noticed the permissions issue.

So, the best I can currently suggest is that you set the ownership of the filter/jmol/temp directory only (i.e. not the rest of the moodle folders) to apache. I'll update the documentation to reflect this

**Comment by jmbragg** [comment]
Yeah, I've got it working right now as long as I get rid of the file aliases.  Sadly my entire Book full of 50 or so different molecules are all aliased so I've got to fix all of those manually.

**Comment by geoffrowland** [comment]
Hope the new features make this worthwhile!
https://moodle.org/mod/forum/discuss.php?d=319666
Since you are going though the effort of 'fixing' 50 molecules, and assuming you are not using it already, you may wish to try the PNGJ format for your data files. 

PNGJ is a compressed package format that wraps a 'snapshot' png image and state inormation with the structure file. The png image provides a 'cover image' to a filtered instance in Moodle and the state provides an alternative way of storing JmolScript commands. To work with the Moodle Jmol filter, they need an appropriate double file extension e.g. .mol.png, .pdb.png, .cif.png. Some more details in the above link.

**Comment by abstr4kt** [comment]
Hi there,
i've got the same problem of PatLemaire on my Moodle installation:
Moodle 2.9.1 + Jmol 2015100500  on Nginx 
I noticed an error, in the Nginx realted log file:

[error] 25666#0: *94658 open() "/var/www/localhost/htdocs/filter/jmol/temp" failed (2: No such file or directory)..... request: "GET /filter/jmol/temp?file=/396/mod_book/chapter/63/NaCl.cif

under /filter/jmol/  folder i  found a folder named:

/temp?file=/

that contain jmol files (.cif,.xyz etc).
So i manually added temp folder (empty one) under jmol and error in log file turned off but i still get  "unrecognized file format" message.

I append my nginx.conf :




server {
                listen 80;
                client_max_body_size 180M;
                server_name myserver.it ;
                access_log /var/log/nginx/myserver.access_log main;
                error_log /var/log/nginx/myserver.error_log info;
                root /var/www/localhost/htdocs/;
                index index.php ;
                rewrite ^/draftfile.php/(.*)$ /file.php?file=/$1 last;
                rewrite ^/user/pix.php(.*)$ /user/pix.php?file=/$1 last;
                #moodle hack
                rewrite ^(.*\.php)(/)(.*)$ $1?file=/$3 last;
                if (!-e $request_filename) {
                        set $filephp 1;
                        }
                # If the missing file is a php folder URL
                if ($request_filename ~ "\.php/") {
                        set $filephp "${filephp}1";
                        }
                # Non-existing URL based on PHP script
                # Rewrite the URL to the base PHP script requesting
                if ($filephp = 11) {
                        rewrite ^(.*).php/.*$ /$1.php last;
                        break;
                        }

                autoindex on;

                location ~ \.flv$ {
                            flv;
                            }
location ~ .*.php$ {
                                include /etc/nginx/fastcgi.conf;
                                fastcgi_pass  127.0.0.1:1234;
                                fastcgi_read_timeout 300;
                                fastcgi_index index.php;
                                fastcgi_param SCRIPT_FILENAME /var/www/localhost/htdocs$fastcgi_script_name;
                                }
                        }


What am i missing?
Thanks in advance.

**Comment by geoffrowland** [comment]
No experience with Nginx, just Apache. So can't provide specific help :-(
However, in general terms:
The 'cache' folder should just be filter/jmol/temp
This folder needs appropriate ownership and permissions to be readable and writeable by the web-server process, which may be apache, nobody, www-data or something else - depending on your server set-up.

**Comment by abstr4kt** [comment]
Thanks for reply, 
I have also tryed to downgrade to jmol4.2 whit no luck.
The filter/jmol/temp folder is set whit the right permission, i also tryed giving  777 (just for try) but nothing changed the  folder remained empty and error message "unrecongnized file format" still there.
Do you belive that can be a Nginx related problem?

**Comment by geoffrowland** [comment]
As I mentioned before, I have no experience of Nginx. So, can't offer much help. That said, I am interested in the (potential) performance advantages on Nginx and hope to have a look at this. Probably not any time soon, though.

Heads - up!

Following all the informative feedback here (thanks to all!) I have been experimenting with removing the problematic temp 'cache' entirely. In general, this makes things much more straight forward. I can get things to work for JSmol (HTML5, JavaScript) with recent browser versions (MS Edge, Chrome, Chromium, Firefox, Opera - not tested Safari). 

However, I am aware that institutions may be 'locked' into older browser versions, particularly MS Internet Explorer 11 or earlier. IE 11 and older versions of Chrome do not currently work (without the temp cache) for binary format structure files. A workaround (used in the previous version of the filter) may be to render with Jmol (Java does not have the binary file loading problem) in these (dwindling?) cases. Of course Java applets are not without their problems! Currently, think that this is the best compromise, though am open to suggestions.

I'll continue testing and hope to release a new version, without the temp cache, in the near future (next day or so?). 

If/when this happens, I'll 'park' the current version as a Git branch, in case I, or anyone else, wants to resurrect the temp 'cache'.

**Comment by abstr4kt** [comment]
I just fixed  my case:
i edited the filter.php in this way:

line 156
from

    $shortpath = str_replace($wwwroot.'/pluginfile.php', '', $url);

to

     $shortpath = str_replace($wwwroot.'/pluginfile.php?file=', '', $url);

and now it work as aspected : the files are copied in the temp folder and jmol show no  more error.
This patch worked fine whit Jmol 2015100500 but also on Jmol 2015091800 (simply update the filetr.php file as above)

hope this help

cheers

**Comment by geoffrowland** [comment]
Thanks @abstr4kt,

Interesting! though I don't understand why it works. :-(

In my hands $url is of the form:

'http://mydomain/moodle/pluginfile.php/33/mod_book/intro/1BNA.pdb.png'

and the corresponding $shortpath: '/33/mod_book/intro/1BNA.pdb.png'

Whereas, if I understand you correctly, you would seem to have, for $url, something like:
http://localhost/moodle27/pluginfile.php?file='/33/mod_book/intro/1BNA.pdb.png'

Not sure what's different?


The Moodle File API (https://docs.moodle.org/dev/File_API) has no mention of the '?file=': part.

Serving files to users

You must refer to the file with a URL that includes a file-serving script, often pluginfile.php. For example

The general form of the URL is something like

$url = $CFG->wwwroot/pluginfile.php/$contextid/$component/$filearea/arbitrary/extra/infomation.ext

A specific example might be

$url = $CFG->wwwroot/pluginfile.php/$forumcontextid/mod_forum/post/$postid/image.jpg

**Comment by jmbragg** [comment]
Geoff, I think your plan of getting rid of the temp cache is probably a good one.  The only thing I would add a suggestion is that you might display a message to the old browser users suggesting a modern browser will help get away from the Java application.  Otherwise an IE11 user might not realize that an upgrade would help with that.

**Comment by geoffrowland** [comment]
Yes, that's a good idea. I'm currently experimenting with browser (capability) detection.

**Comment by geoffrowland** [comment]
Hi folks, I have just updated the master branch with a new version of the J(S)mol filter which no longer needs the temp file folder. Attempts to give more useful feedback on browser version and rendering technology (HTML5, WebGL or Java) issues. Have also included a few other bug-fixes and interface improvements.
Currently bundled with the latest J(S)mol 14.2 as I am still getting a few issues with the recently released 14.4 version. Works with Moodle 3.0 rc2. So, hopefully will work with the soon-to-be-released Moodle 3.0.
In my hands, works well with recent browser versions (Firefox, Chrome, Opera, Safari, Edge) though Java support has, or soon will be, removed from these. JSmol (HTML5) has all the capabilities of Jmol (Java) though is somewhat slower (noticeable with larger biopolymers). GLmol (WebGL) does not have all the J(S)mol capabilities but (for browsers/hardware that support it) but does offer good performance for larger chemical structures.
If this is does not have major issues (feedback is most welcome!) I'll release this in the Moodle plugins directory too.
Cheers

**Comment by geoffrowland** [comment]
I have tried this on the Moodle 3.0 release and not encountered any further issues. 
So, released on the Moodle plugins directory too. Should, at least, now get a wider testing ;-)

**Comment by srfdino** [comment]
Thanks Geoff!
I had no option to make the test in my environment by now, but I'll let you know soon.
Good Work!!

**Comment by geoffrowland** [comment]
Am closing this as had no further issues have been reported with the browser/feature detection 'hacks' and, anyway, these should become less relevant with new browser versions. Have also released anew filter version 6.1 with a few refinements and Jmo/JSmol 14.4.1 bundled.
